# Generated by Django 3.0.7 on 2020-06-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Compra', models.IntegerField()),
                ('wppnmr', models.IntegerField()),
                ('ds_compra', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'lista',
            },
        ),
    ]
